apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: node-js-container
        image: salma22/nodejs-app
        ports:
        - containerPort: 3000
